### ISSUE TITLE
Remove locize integration

### ISSUE THREAD

**Issue by Keith-CY** [citahub/microscope-v2#31]
The locize told me they were receiving requests from our site, but I've checked it has been removed from our code.

@travis-joe could you please have a look? Thanks.

**Comment by adrai** [comment]
This seems to be the relevant code line: https://github.com/citahub/microscope/blob/9264f3e4d53b65f7fe9e37ca0ddeddf1805dab3c/src/templates/index.html#L132

**Comment by Keith-CY** [comment]
Most requests are from https://microscope.ipaynow.cn/ according to the report, please ask them to upgrade to v2 if possible @travis-joe, thanks.

**Comment by rainchen** [comment]
@travis-joe is this issue resolved?

**Comment by travis-joe** [comment]
it's resolved.
